### PR TITLE
News Articles MVP Finish

### PR DESCRIPTION
**Pull request by CeeFM**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests
- [X] Test A - You can add and delete articles from the articles module
- [X] Test B - Newest articles should appear on top
- [X] Test C - Login, logout, and register buttons don't refresh/reload the page because the instructors be mad goofin and stuff
# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by darrindoc** [comment]
I was able to sign in, add an article, delete the article and sign out. I approve 😎

**Review by NorwoodH — APPROVED** [review]

**Review by NorwoodH — APPROVED** [review]
works as intended when tested.

**Review by darrindoc — APPROVED** [review]
**Comment**

**Comment by Mariiaq5** [comment]
Good job👍🏼

**Pull request merged**
